on: 
  push:
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # updated on Jan 16
    - uses: msys2/setup-msys2@a5d2c5a565c520efa5f477391e4e3f87c2e08f46 # updated on Apr 14
      with:
        msystem: UCRT64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc 
          make
        
    - run: make -j$(nproc)
      shell: msys2 {0}
