on: 
  push:
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # updated on Jan 16
      
      
      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@61f9e5e925871ba6c9e3e8da24ede83ea27fa91f # v2.27.0 
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            make
            
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y build-essential gcc-14 make

        
      - if: matrix.os == 'windows-latest'
        run: make -j$(nproc)
        shell: msys2 {0}
      
      - if: matrix.os == 'ubuntu-latest'
        run: make -j$(nproc)
        # assume bash
