name: MSYS2 CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-gcc 
    - run: g++ -std=c++23 -O0 -g main.cpp .\\include\\sqlite3.o -o main.exe -lws2_32 -lwinmm -lpthread
      shell: msys2 {0}