name: MSYS2 CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-gcc 
    - run: g++ -std=c++23 -O0 -I ./include/enet -g main.cpp ./include/enet/callbacks.c ./include/enet/compress.c ./include/enet/host.c ./include/enet/list.c ./include/enet/packet.c ./include/enet/peer.c ./include/enet/protocol.c ./include/enet/win32.c -o main.exe -lws2_32 -lwinmm
      shell: msys2 {0}